
import { 
  Home, 
  Users, 
  Settings, 
  LogOut, 
  Bell, 
  Moon, 
  Sun, 
  CircleUser, 
  ShieldCheck, 
  Menu, 
  Search, 
  ArrowRight, 
  Plus, 
  Trash2, 
  Pencil, 
  X, 
  Lock, 
  Eye, 
  EyeOff, 
  Mail, 
  IdCard, 
  LayoutDashboard, 
  ChevronDown, 
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  PanelLeftClose,
  PanelLeft
} from 'lucide-react';

export const Icons = {
  Home: Home,
  Users: Users,
  Settings: Settings,
  Logout: LogOut,
  Bell: Bell,
  Moon: Moon,
  Sun: Sun,
  User: CircleUser,
  Shield: ShieldCheck,
  Menu: Menu,
  Search: Search,
  ArrowRight: ArrowRight,
  ArrowLeft: ArrowLeft,
  Plus: Plus,
  Trash: Trash2,
  Edit: Pencil,
  Close: X,
  Lock: Lock,
  Eye: Eye,
  EyeSlash: EyeOff,
  Email: Mail,
  ID: IdCard,
  Dashboard: LayoutDashboard,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  SidebarClose: PanelLeftClose,
  SidebarOpen: PanelLeft,
};
